apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"gpte.opentlc.com/v1alpha1","kind":"Nexus","metadata":{"name":"example-nexus"},"spec":{"nexusCpuLimit":2,"nexusCpuRequest":1,"nexusImageTag":"latest","nexusMemoryLimit":"2Gi","nexusMemoryRequest":"2Gi","nexusSsl":true,"nexusVolumeSize":"10Gi"}}]'
    capabilities: Repository management
    categories: Repository management
    certified: 'false'
    containerImage: quay.io/gpte-devops-automation/nexus-operator:v0.9.0
    createdAt: 2019-04-30 12:39:00
    description: The world's best way to organize, store, and distribute software components.
  name: nexus-operator.v0.9.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Nexus
      name: nexus.gpte.opentlc.com
      version: v1alpha1
      description: Represents a nexus repository
      displayName: Nexus
  description: Placeholder description
  displayName: Nexus Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - update
          - delete
          - get
          - list
          - watch
          - patch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - update
          - delete
          - get
          - list
          - watch
          - patch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - update
          - delete
          - get
          - list
          - watch
          - patch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - gpte.opentlc.com
          resources:
          - nexus
          - nexus/status
          verbs:
          - create
          - update
          - delete
          - get
          - list
          - watch
          - patch
        - apiGroups:
          - apps
          resourceNames:
          - nexus-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        serviceAccountName: nexus-operator
      deployments:
      - name: nexus-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: nexus-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: nexus-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: quay.io/gpte-devops-automation/nexus-operator:v0.9.0
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: userquota-operator
                image: quay.io/gpte-devops-automation/nexus-operator:v0.9.0
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: nexus-operator
              volumes:
              - emptyDir: {}
                name: runner
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.9.0
