apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pushapplications.push.aerogear.org
spec:
  group: push.aerogear.org
  names:
    kind: PushApplication
    listKind: PushApplicationList
    plural: pushapplications
    singular: pushapplication
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              description: Description is a description of the app to be displayed
                in the UnifiedPush Server admin UI
              type: string
          required:
          - description
          type: object
        status:
          properties:
            masterSecret:
              description: MasterSecret is a master password, used for sending message
                to this PushApplication, or it's Variant(s)
              type: string
            pushApplicationId:
              description: PushApplicationId is an identifer used to register Variants
                with this PushApplication
              type: string
            variants:
              description: Variants is a slice of variant (AndroidVariant or IOSVariant,
                in this package) names associated with this Application
              items:
                type: string
              type: array
          required:
          - pushApplicationId
          - masterSecret
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
