language: go

sudo: required

go:
- 1.12.x

env:
  global:
    - OPERATOR_NAME=integreatly-operator

stages:
- name: push
  if: fork = false AND branch = master

jobs:
  include:
  - stage: push
    script:
    - docker login --password "$QUAY_PASSWORD" --username "$QUAY_USERNAME" quay.io
    - export TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then make setup/dep setup/travis image/build/push; else make setup/dep setup/travis image/build/push TAG=$TAG; fi