
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: rhmi-operator-metrics
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: http-metrics
  selector:
    matchLabels:
      control-plane: controller-manager
