apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: operator-metrics
  namespace: system
spec:
  ports:
  - name: http-metrics
    port: 8383
    targetPort: 8383
  selector:
    control-plane: controller-manager
