apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: integreatly-operator
rules:
- apiGroups:
  - batch
  resources:
    - cronjobs
  verbs:
    - create
    - update
- apiGroups:
    - "rbac.authorization.k8s.io"
  resources:
    - "clusterroles"
    - "clusterrolebindings"
  verbs:
    - create
    - update
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - get
    - list
- apiGroups:
    - ""
  resources:
    - "pods/exec"
  verbs:
    - create
    - update
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - list
    - get
    - create
    - watch
- apiGroups:
    - operators.coreos.com
  resources:
    - catalogsourceconfigs
  verbs:
    - list
    - create
    - watch
- apiGroups:
    - ""
  resources:
    - pods
    - secrets
  verbs:
    - list
    - get
- apiGroups:
    - operators.coreos.com
  resources:
    - catalogsourceconfigs/finalizers
  verbs:
    - '*'
- apiGroups:
    - operators.coreos.com
  resources:
    - operatorgroups
    - subscriptions
    - installplans
  verbs:
    - list
    - create
    - watch
    - get
- apiGroups:
    - aerogear.org
  resources:
    - keycloaks
    - keycloakrealms
  verbs:
    - list
    - create
    - update
    - watch
    - get
- apiGroups:
    - kafka.strimzi.io
  resources:
    - kafkas
  verbs:
    - list
    - create
    - watch
    - get
- apiGroups:
    - apps.3scale.net
  resources:
    - apimanagers
  verbs:
    - list
    - create
    - watch
    - get
- apiGroups:
    - org.eclipse.che
  resources:
    - checlusters
  verbs:
    - list
    - create
    - watch
    - get