apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: integreatly-operator-subscription
objects:
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: ${OPERATOR_GROUP_NAME}
      namespace: ${NAMESPACE}
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: ${SUBSCRIPTION_NAME}
      namespace: ${NAMESPACE}
    spec:
      channel: ${CHANNEL}
      installPlanApproval: Automatic
      name: integreatly
      source: ${CATALOG_SOURCE_CONFIG_NAME}
      sourceNamespace: ${NAMESPACE}

parameters:
  - description: The namespace to deploy into
    displayName: Namespace
    name: NAMESPACE
    value: integreatly
  - description: The name of the catalog source config
    displayName: Catalog Source Config Name
    name: CATALOG_SOURCE_CONFIG_NAME
    value: installed-integreatly-operator
  - description: The name of the catalog source config namespace
    displayName: Catalog Source Config Namespace
    name: CATALOG_SOURCE_CONFIG_NAMESPACE
    value: openshift-marketplace
  - description: The name of the operator group
    displayName: Operator Group Name
    name: OPERATOR_GROUP_NAME
    value: integreatly-operator
  - description: The name of the subscription
    displayName: Subscription Name
    name: SUBSCRIPTION_NAME
    value: integreatly-operator
  - description: The name of the channel
    displayName: Channel Name
    name: CHANNEL
    value: integreatly
