apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: integreatly-deploy
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: ${NAMESPACE_PREFIX}codeready-workspaces
- apiVersion: v1
  kind: Namespace
  metadata:
    name: ${NAMESPACE_PREFIX}amq-streams
- apiVersion: v1
  kind: Namespace
  metadata:
    name: ${NAMESPACE_PREFIX}rhsso
- apiVersion: v1
  kind: Namespace
  metadata:
    name: ${INSTALLATION_NAMESPACE}
- apiVersion: integreatly.org/v1alpha1
  kind: Installation
  metadata:
    name: ${NAMESPACE_PREFIX}integreatly-installation
    namespace: ${INSTALLATION_NAMESPACE}
  spec:
    namespacePrefix: ${NAMESPACE_PREFIX}
    type: workshop
parameters:
- name: INSTALLATION_NAMESPACE
  value: integreatly-operator
- name: NAMESPACE_PREFIX
  value: openshift-
