apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: integreatly-deploy
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: s3-credentials
      namespace: ${INSTALLATION_NAMESPACE}
    stringData:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_BUCKET}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: s3-bucket
      namespace: ${INSTALLATION_NAMESPACE}
    stringData:
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_REGION: ${AWS_REGION}
parameters:
  - name: INSTALLATION_NAMESPACE
    required: true
  - name: AWS_ACCESS_KEY_ID
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    required: true
  - name: AWS_BUCKET
    required: true
  - name: AWS_REGION
    required: true
